language: python

python:
   - 2.6
   - 2.7

install:
   - pip install -r dev_requirements.txt;
   - pip install coveralls

script:
   - bash tools/run_tests.sh

after_success:
    coveralls

notifications:
  email:
    - cournape@gmail.com
