language: python

python:
   - 2.6
   - 2.7
   - 3.2
   - 3.3
   - pypy

install:
   - if [ "${TRAVIS_PYTHON_VERSION}" == "2.6" ]; then
       pip install -r dev_requirements26.txt;
       else
       pip install -r dev_requirements.txt;
       fi
   - pip install coveralls

script:
   - bash tools/run_tests.sh

after_success:
    coveralls

notifications:
  email:
    - cournape@gmail.com
